version: "3"

env:
  AWS_REGION: "${AWS_REGION:-us-east-2}"

vars:
  TF_DIR: "."

silent: false

tasks:
  tf:lock:
    desc: Refresh Terraform provider lock file for local macOS and Linux x86_64.
    cmds:
      - terraform -chdir={{.TF_DIR}} providers lock -platform=${TF_LOCK_DARWIN_PLATFORM:-darwin_arm64} -platform=${TF_LOCK_LINUX_PLATFORM:-linux_amd64}

  tf:fmt:
    desc: Format Terraform files.
    cmds:
      - terraform -chdir={{.TF_DIR}} fmt -recursive

  tf:lint:
    desc: Run tflint.
    cmds:
      - tflint --chdir={{.TF_DIR}}

  tf:validate:
    desc: Terraform validate.
    deps:
      - tf:init
      - tf:fmt
    cmds:
      - terraform -chdir={{.TF_DIR}} validate

  tf:init:
    desc: Terraform init.
    cmds:
      - terraform -chdir={{.TF_DIR}} init

  tf:plan:
    desc: Terraform plan.
    deps:
      - tf:init
      - tf:fmt
    cmds:
      - terraform -chdir={{.TF_DIR}} plan

  tf:apply:
    desc: Terraform apply.
    deps:
      - tf:plan
    cmds:
      - terraform -chdir={{.TF_DIR}} apply
